### ISSUE TITLE
Does not honor Referrer-Policy as a HTTP header

### ISSUE THREAD

**Issue by rugk** [andersju/webbkoll#1]
Webservers can also use HTTP headers to express their referrer policy. However webbkoll does still show the part in red when a HTTP header is used instead of a meta tag.

Tested with: `Referrer-Policy: same-origin`

https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-header

**Comment by andersju** [comment]
Neither Firefox nor Chrome actually supports this in stable versions at the moment (see [1](https://bugzilla.mozilla.org/show_bug.cgi?id=1264164), [2](https://bugs.chromium.org/p/chromium/issues/detail?id=619228)), although they will soon-ish. It reminds me however that they do support the older [CSP referrer directive](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#referrer) - I'll add support for this. Thanks!

**Comment by rugk** [comment]
Would you mind keeping this issue open for implementing the "Referrer-Policy" header when Firefox and/or Chrome finally support it?

**Comment by andersju** [comment]
Ah, yes, of course! Too little sleep lately...

**Comment by andersju** [comment]
Fixed but not live on webbkoll.dataskydd.net yet - Firefox has "basic support" since version 50 (current) but won't support same-origin until 52 (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy#Browser_compatibility) and Chrome will support it from next version, 56 (https://www.chromestatus.com/features/5639972996513792), so I'll wait a bit.
