### ISSUE TITLE
Internationalized Domain Names (IDN) not recognized

### ISSUE THREAD

**Issue by ghost** [andersju/webbkoll#34]
Hi,

I have tried testing one domain using punycode and Webbkoll service returned that domain is invalid.
Is there a chance to allow Internationalized Domain Names (IDN) in punycode form?

[Edit]

It seems that service recognise redirection from regular to IDN domain which is a bit unusual : )

**Comment by andersju** [comment]
Shouldn't be a problem. E.g. https://räksmörgås.josefsson.org/ (https://xn--rksmrgs-5wao1o.josefsson.org/) works fine. "Invalid domain" is usually due to a new TLD that's not in our copy of the public suffix list (meaning we should update it :)).

Please give me an example of a domain that doesn't work. Email anders@unix.se if you don't want to mention it here.

**Comment by andersju** [comment]
It was indeed a problem; IDN _TLDs_ didn't work, but should work now (b47305c). Thanks!
